// PREVIEW ONLY. Fabricated records for demoing the finished flow. Not real providers or prices.
// The PRD forbids fabricated data in the real demo; this file is loaded only when PREVIEW is on.
import type { Rec } from "./records.ts";

const c = "2026-09-04T09:10:00+08:00";
const base = { mandatory_fees_twd: 0, discount_twd: 0, eligibility: [] as string[], registration_required: false, collected_at: c, source_url: "#", baseline: null };

export const MOCK_RECORDS: Rec[] = [
  // 食品
  { ...base, id: "f1", category: "食品", agent: "paid", title: "雙人便當組合", provider: "示範便當店", price_total_twd: 260, price_unit: "每人 NT$130", quantity_or_servings: "2 人份", availability_or_event_time: "17:00 後供應", distance_or_time_text: "步行約 12 分鐘", eligibility: ["可外帶"], source_type: "curated", source_authority: "provider", evidence_quote: "雙人組合 260 元，含兩份主餐與湯。", verified_at: "2026-09-03", data_status: "已驗證", action_label: "查看菜單", baseline: { name: "在地常見方案（兩份單點便當）", total_twd: 300, basis: "同為 2 人份、可外帶", as_of: "2026-09-03" } },
  { ...base, id: "f2", category: "食品", agent: "paid", title: "自助餐兩人份", provider: "示範自助餐", price_total_twd: 290, price_unit: "每人 NT$145", quantity_or_servings: "2 人份（估）", availability_or_event_time: "11:00–20:00", distance_or_time_text: "1.6 km", source_type: "web-searched", source_authority: "other", evidence_quote: "平均一人約 140 至 150 元。", verified_at: "2026-09-02", data_status: "部分驗證／待確認", action_label: "查看來源" },
  { ...base, id: "f3", category: "食品", agent: "paid", title: "鍋物雙人套餐", provider: "示範鍋物", price_total_twd: 399, mandatory_fees_twd: 40, price_unit: "每人 NT$219.5", quantity_or_servings: "2 人份", availability_or_event_time: "17:30–22:00", distance_or_time_text: "2.4 km", eligibility: ["內用", "10% 服務費"], source_type: "curated", source_authority: "provider", evidence_quote: "雙人套餐 399 元，另收一成服務費。", verified_at: "2026-09-04", data_status: "已驗證", action_label: "查看菜單" },
  { ...base, id: "f4", category: "食品", agent: "paid", title: "水餃 20 顆", provider: "示範水餃店", price_total_twd: 160, price_unit: "每顆 NT$8", quantity_or_servings: "20 顆（約 2 人）", availability_or_event_time: "全日", distance_or_time_text: "步行約 8 分鐘", eligibility: ["可外帶"], source_type: "curated", source_authority: "provider", evidence_quote: "韭菜水餃 8 元／顆，外帶可。", verified_at: "2026-09-04", data_status: "已驗證", action_label: "查看菜單", baseline: { name: "使用者原方案（超商 2 份微波餐）", total_twd: 218, basis: "同為 2 人份", as_of: "2026-09-04" } },
  // 日用品
  { ...base, id: "d1", category: "日用品", agent: "paid", title: "洗衣精 2L 兩入", provider: "示範量販", price_total_twd: 318, price_unit: "每公升 NT$79.5", quantity_or_servings: "4 L", availability_or_event_time: "9/1–9/14", distance_or_time_text: "2.0 km", eligibility: ["需會員"], source_type: "curated", source_authority: "official", evidence_quote: "兩入特價 318 元，9/1 至 9/14。", verified_at: "2026-09-04", data_status: "已驗證", action_label: "查看 DM", baseline: { name: "Costco 基準（同品 3L）", total_twd: 255, basis: "換算為每公升後比較", as_of: "2026-09-01" } },
  { ...base, id: "d2", category: "日用品", agent: "paid", title: "衛生紙 12 抽 x 6 包", provider: "示範藥妝", price_total_twd: 129, price_unit: "每包 NT$21.5", quantity_or_servings: "6 包", availability_or_event_time: "全日", distance_or_time_text: "步行約 10 分鐘", source_type: "web-searched", source_authority: "provider", evidence_quote: "6 包裝 129 元。", verified_at: "2026-09-03", data_status: "已驗證", action_label: "查看商品" },
  { ...base, id: "d3", category: "日用品", agent: "paid", title: "洗碗精 1L", provider: "示範超市", price_total_twd: null, price_unit: null, quantity_or_servings: "1 L", availability_or_event_time: null, distance_or_time_text: "1.1 km", source_type: "web-searched", source_authority: "other", evidence_quote: "頁面未列價格。", verified_at: "2026-09-02", data_status: "無法納入比較", action_label: "查看來源" },
  // 免費／公益資源
  { ...base, id: "r1", category: "免費／公益資源", agent: "free", title: "社區共餐（週六）", provider: "示範里辦公處", price_total_twd: 0, price_unit: null, quantity_or_servings: "限 30 名", registration_required: true, eligibility: ["需前一天登記", "設籍或在地工作者"], availability_or_event_time: "週六 12:00–13:00", distance_or_time_text: "圓山區內", source_type: "curated", source_authority: "public", evidence_quote: "每週六提供免費共餐，請於週五前來電登記。", verified_at: "2026-09-03", data_status: "已驗證", action_label: "查看公告" },
  { ...base, id: "r2", category: "免費／公益資源", agent: "free", title: "圖書館自習室", provider: "示範圖書分館", price_total_twd: 0, price_unit: null, quantity_or_servings: "60 席", eligibility: ["持借書證"], availability_or_event_time: "09:00–21:00", distance_or_time_text: "1.3 km", source_type: "curated", source_authority: "official", evidence_quote: "自習室免費使用，憑證入座。", verified_at: "2026-09-04", data_status: "已驗證", action_label: "查看開放時間" },
  { ...base, id: "r3", category: "免費／公益資源", agent: "free", title: "公園免費瑜伽", provider: "示範運動中心", price_total_twd: 0, price_unit: null, quantity_or_servings: null, eligibility: ["自備墊子"], availability_or_event_time: "週日 08:00", distance_or_time_text: "1.2 km", source_type: "web-searched", source_authority: "other", evidence_quote: "免費參加，無需報名。（活動頁日期為 8 月）", verified_at: "2026-09-01", data_status: "過期／待確認", action_label: "查看活動頁" },
  // 活動
  { ...base, id: "a1", category: "活動", agent: "free", title: "週末市集", provider: "示範文創園區", price_total_twd: 0, price_unit: null, quantity_or_servings: null, eligibility: ["免門票", "攤位消費另計"], availability_or_event_time: "9/6–9/7 11:00–19:00", distance_or_time_text: "1.8 km", source_type: "curated", source_authority: "official", evidence_quote: "9/6 至 9/7，免費入場。", verified_at: "2026-09-04", data_status: "已驗證", action_label: "查看活動" },
  { ...base, id: "a2", category: "活動", agent: "paid", title: "當代藝術特展", provider: "示範美術館", price_total_twd: 200, discount_twd: 50, price_unit: "每人 NT$150（學生）", quantity_or_servings: "1 人", eligibility: ["學生票需證件"], availability_or_event_time: "10:00–18:00，週一休", distance_or_time_text: "2.2 km", source_type: "curated", source_authority: "official", evidence_quote: "全票 200 元，學生票 150 元。", verified_at: "2026-09-04", data_status: "已驗證", action_label: "購票" },
  { ...base, id: "a3", category: "活動", agent: "paid", title: "手作講座", provider: "示範社區大學", price_total_twd: 300, price_unit: "每人 NT$300", quantity_or_servings: "1 人", eligibility: ["材料費另計（未列）"], availability_or_event_time: "9/7 14:00", distance_or_time_text: "1.5 km", source_type: "web-searched", source_authority: "provider", evidence_quote: "報名費 300 元，材料費現場收取。", verified_at: "2026-09-02", data_status: "衝突待確認", action_label: "查看報名頁" },
  // 交通
  { ...base, id: "t1", category: "交通", agent: "paid", title: "公車單程", provider: "示範客運", price_total_twd: 15, price_unit: "每人每段 NT$15", quantity_or_servings: "1 人", eligibility: ["電子票證"], availability_or_event_time: "05:30–23:00", distance_or_time_text: "圓山區內多站", source_type: "curated", source_authority: "official", evidence_quote: "一段票 15 元。", verified_at: "2026-08-30", data_status: "已驗證", action_label: "查看票價" },
  { ...base, id: "t2", category: "交通", agent: "paid", title: "共享單車 30 分鐘", provider: "示範共享單車", price_total_twd: 10, price_unit: "每 30 分鐘 NT$10", quantity_or_servings: "1 人", eligibility: ["需註冊", "前 30 分鐘優惠依站點"], availability_or_event_time: "24 小時", distance_or_time_text: "站點約 400 m", source_type: "web-searched", source_authority: "official", evidence_quote: "前 30 分鐘 10 元。", verified_at: "2026-09-01", data_status: "部分驗證／待確認", action_label: "查看站點" },
];
